name: GitHub Actions Practica

on: [push]

jobs:
  Explorando-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo El flujo de trabajo ha sido ejecutado
      - run: echo El trabajo se esta ejecutando en GitHub
      - run: echo Mostrando informacion del repositorio
      
      - name: Verifica el codigo del repositorio
        uses: actions/checkout@v2
      
      - name: Listar archivos en el repositorio
        run: ls
      
      - run: echo El estado del trabajo es success
